<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pysystest state="runnable" type="auto">
	<description>
		<title>Slicer 009 : Testing by configuring two Slicers for Param 'sliceType' set to 'sliceCount' and 'sliceSize' each and receiving data events from two sources.</title>
		<purpose>
		<![CDATA[Config validation errors.]]>
		</purpose>
	</description>
	<classification>
		<groups>
			<group>Slicer</group>
			<group>Flow_Manipulation</group>
			<group>Industry_Analytics</group>
			<group>EPL</group>
		</groups>
	</classification>
	<data>
		<class module="run" name="PySysTest"></class>
	</data>
	<traceability>
		<requirements>
			<requirement></requirement>
		</requirements>
	</traceability>
</pysystest>