<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pysystest state="runnable" type="auto">
	<description>
		<title>GeoFence 001: Config validation errors</title>
		<purpose>
		<![CDATA[Config validation errors.]]>
		</purpose>
	</description>
	<classification>
		<groups>
			<group>GeoFence</group>
			<group>GeoLocation</group>
			<group>Industry_Analytics</group>
			<group>EPL</group>
		</groups>
	</classification>
	<data>
		<class module="run" name="PySysTest"></class>
	</data>
	<traceability>
		<requirements>
			<requirement></requirement>
		</requirements>
	</traceability>
</pysystest>